### ISSUE TITLE
Homebrewのインストール

### ISSUE THREAD

**Issue by ik256** [ik256/on-boarding#3]
### 参考にしたサイト
>https://original-game.com/how-to-install-homebrew/

1. App Storeにあるか検索してみた → なかった
2. インストールの方法を調べる
3. ターミナルを使ってインストールをするらしい
4. Homebrew公式サイトに移動　/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"　このコードをコピー
5. ターミナルを起動し、コードをペーストする　パスワードを聞かれるので入力して続行
6. PATHを通す必要がある　echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/*/.zprofile                                                         eval "$(/opt/homebrew/bin/brew shellenv)"を1行ずつ実行
7. brew -wでバージョンを見ることができたのでインストールに成功したことが確認できた。

**Comment by ofl** [comment]
## brew コマンドを使ってみる

- brew list
- brew update
- brew upgrade

## Brewfileの使い方を調べる

**Comment by ik256** [comment]
## brew　コマンドを使ってみる

brew listコマンドを使うとgettext	git	pcre2 が表示されました。
brew updateはhome brew本体の更新 brew upgradeはhome brew本体だけでなく、home brewにインストールされているパッケージも更新することを知りました。

## Brewfileの使い方を調べる
### 参考にしたサイト
>　https://qiita.com/d0ne1s/items/90974ad472c2d891e784
>    https://webrandum.net/brewfile/

gitなどのコマンドラインで使うツール、インストーラーを使って入れるアプリ、AppStore経由で入れるアプリがコマンド一つでインストールできる。

brew bundle dumpのコマンドを実行すれば、自動で現在の環境に合わせてBrewfileが生成されました。
